### ISSUE TITLE
About model_name

### ISSUE THREAD

**Issue by jinsikbang** [lbaa2022/LLMTaskPlanning#1]
Hi there,

Thank you for your excellent work.

To test GPT-3 and GPT-3.5 using your code, how should I specify the model name? 
I can't seem to find it.

Attempted options:
text-davinci-003
OpenAI/text-davinci-003
OpenAI/gpt-3.5

However, GPT4(OPenAI/gpt-4) works.

**Comment by youngwoo-yoon** [comment]
Hello,
`text-davinci-003` is no longer available. See https://community.openai.com/t/text-davinci-003-deprecated/582617
Instead, you can use `OpenAI/gpt-3.5-turbo-instruct` as the model name in the configuration file. I have just updated the code to be compatible with it. Please pull the latest changes.

Note that `gpt-3.5-turbo-instruct` works as a replacement for `text-davinci-003` but `gpt-3.5-turbo` does not, as it operates only in chat mode.

**Comment by jinsikbang** [comment]
Thanks, it works.

However, I have another issue. When I extract train samples data for finetuning, some lines are commented out in "extract_alfred_train_samples.py". 
Even if I uncomment them, the variables example_selected and prompt do not exist.

Is the "extract_alfred_train_samples.py" file still incomplete yet?

**Comment by youngwoo-yoon** [comment]
Sorry for the confusion. Please use `src/alfred/examine_alfred_data.py` to extract training samples. You can use output txt file for finetuning.
