### ISSUE TITLE
No files src/misc/extract_alfred_train_samples.py referred in README.md

### ISSUE THREAD

**Issue by lziiid** [lbaa2022/LLMTaskPlanning#3]
Thanks for your open-sourced work! I want to fine-tune my model on Alfred, but the file extract_alfred_train_samples.py  is not provided in the code.

**Comment by youngwoo-yoon** [comment]
Sorry for the incorrect instruction. Please use src/alfred/exmaine_alfred_data.py script. I've updated the readme file as well.
