### ISSUE TITLE
ImportError: libGl.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Dacossti** [lbaa2022/LLMTaskPlanning#4]
Hello, everyone!
Could you please help me figure out what's wrong here?

![photo_2024-06-12_06-56-28](https://github.com/lbaa2022/LLMTaskPlanning/assets/104396909/8de0a7dc-97e1-4d8f-bb66-bb25f67c8b44)

**Comment by youngwoo-yoon** [comment]
I think opencv is not properly installed. Please try install opencv-python again.
