### ISSUE TITLE
About success rate in gpt-4

### ISSUE THREAD

**Issue by Tziy** [lbaa2022/LLMTaskPlanning#7]
Hello, excellent work! 
I want to follow your work, but when using GPT-4, I found that the success rate (success rate: 6.82 %, average subgoal success rate: 35.74%)is different from what's in the paper's appendix. I'm wondering if there's an issue with my settings somewhere? Below are my log, thank you!

[2024-10-11 19:04:05,663][wah.wah_evaluator][INFO] - planner:
  model_name: OpenAI/gpt-4
  use_accelerate_device_map: true
  load_in_8bit: false
  device: cuda
  max_steps: 30
  random_seed: 0
  scoring_batch_size: 10
  score_function: sum
  scoring_mode: guidance
  use_predefined_prompt: false
  hf_auth_token: false
  openai_api_key: 
  openai_api_base: 
  nl_act_list:
  - find
  - pick up
  - open
  - close
  - switch on
  - put down
  dynamic_skill_set: false
name: wah
out_dir: ${hydra:run.dir}
prompt:
  num_examples: 5
  splitter: ''
  prefix: 'Robot: Hi there, I''m a robot operating in a home.

    Robot: You can ask me to do various tasks and I''ll tell you the sequence of actions
    I would do to accomplish your task.

    '
  example_file_path: resource/wah_examples_for_prompt_default.json
  seed: 0
  select_method: uniform
dataset:
  wah_testset: dataset/wah_nl_test.json
  wah_trainset: dataset/wah_nl_train.json
  obj_dict_sim2nl: resource/wah_objects_sim2nl.json
  obj_dict_nl2sim: resource/wah_objects_nl2sim.json
experiment:
  exp_name: benchmark_wah_nl
environment:
  observation_types:
  - full
  use_editor: true
  base_port: 8080
  port_id: 1
  executable_args:
    file_name: virtualhome/simulation/unity_simulator/linux_exec.x86_64
  recording_options:
    recording: false
    output_folder: ../../../figure
    file_name_prefix: Test
    cameras:
    - PERSON_FROM_BACK

**Comment by youngwoo-yoon** [comment]
Hello,
It seems your result is correct. We reported a subgoal success rate of 34.17% for WAH-NL in the paper, which is quite similar to your results. Some differences may exist as GPT-4 is updated frequently.

**Comment by Tziy** [comment]
> Hello, It seems your result is correct. We reported a subgoal success rate of 34.17% for WAH-NL in the paper, which is quite similar to your results. Some differences may exist as GPT-4 is updated frequently.

Thank you for your quick response, it confirms that my settings are correct.
