### ISSUE TITLE
About deploy Saycan in WAH-NL benchmark

### ISSUE THREAD

**Issue by Tziy** [lbaa2022/LLMTaskPlanning#8]
Hello, I've been following your work recently and noticed in your appendix that SayCan achieved a 21.65% Success Rate with GPT-Neo 6B in the WAH-NL benchmark. Could you please explain how you deployed SayCan in the WAH-NL benchmark? I'm also interested in learning about the performance of other LLMs using SayCan in the WAH-NL benchmark. Are there any details you can share about this? Thank you for your response!

**Comment by youngwoo-yoon** [comment]
Hello, you can set `scoring_mode: 'naive'` in the config to use saycan's implementation. Please refer to the code for the details.

**Comment by Tziy** [comment]
> Hello, you can set `scoring_mode: 'naive'` in the config to use saycan's implementation. Please refer to the code for the details.

Thank you for your response. I've noticed that if I want to test using the naive mode, I need to set step_by_step_mode to True. However, this isn't available for the ChatGPT series models. Does this mean I can simply replace the self.guidance_program-related content in plan_step_by_step with direct calls to the ChatGPT API to obtain the evaluation results for SayCan? Thank you again for your explanation.

**Comment by youngwoo-yoon** [comment]
Yes, you're right. At the time of development, `logprobs` was supported only in base models (e.g., GPT 3), not chat models (e.g., GPT 3.5). As this is now available, I think you can implement it for the chat models.

**Comment by Tziy** [comment]
> Yes, you're right. At the time of development, `logprobs` was supported only in base models (e.g., GPT 3), not chat models (e.g., GPT 3.5). As this is now available, I think you can implement it for the chat models.

Thank you for your quick response! I'll try it.
